In [2]:
"""
Examples of creating and using anonymous functions.
"""

import random

# Easily create a list of numbers
data = list(range(10))
print("range data:", data)

def square(val):
    return val ** 2

# Square all numbers in the list
squares = list(map(square, data))
print("squares:", squares)

# Double all numbers in the list
doubles = list(map(lambda num: num * 2, data))
print("doubles:", doubles)

# Create a list of random numbers (list comprehension)
randnums = [random.randrange(2, num+3) for num in range(10)]
print("random numbers:", randnums)

# Create a list of tuples
tups = list(map(lambda num1, num2: (num1, num2), data, randnums))
print("tuples:", tups)

# Create a list of the min values in the tuples
mins = list(map(lambda pair: min(pair[0], pair[1]), tups))
print("minimums:", mins)

# Create a list only of tuples where the second item is less than the first
newtups = list(filter(lambda pair: pair[1] < pair[0], tups))
print("filtered:", newtups)

range data: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
squares: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
doubles: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
random numbers: [2, 2, 2, 2, 6, 7, 5, 6, 7, 6]
tuples: [(0, 2), (1, 2), (2, 2), (3, 2), (4, 6), (5, 7), (6, 5), (7, 6), (8, 7), (9, 6)]
minimums: [0, 1, 2, 2, 4, 5, 5, 6, 7, 6]
filtered: [(3, 2), (6, 5), (7, 6), (8, 7), (9, 6)]

# More advanced sorting examples.

In [3]:
"""
More advanced sorting examples.
"""

import random

# Easily create a shuffled list of numbers
data = list(range(10))
random.shuffle(data)
print("shuffled data:", data)

# Sort the list of numbers
data.sort()
print("ascending sort:", data)
data.sort(reverse=True)
print("descending sort:", data)

# Create a list of tuples
datatups = [(item, random.randrange(3, 15)) for item in data]
print("data tuples:", datatups)

# Sort the list
datatups.sort()
print("sorted data tuples:", datatups)

datatups.sort(key=lambda pair: pair[1])
print("sorted by second item:", datatups)

datatups.sort(key=lambda pair: pair[0] * pair[1], reverse=True)
print("sorted by product:", datatups)

# Shuffle it again
random.shuffle(datatups)
print("shuffled tuples:", datatups)

# Use sorted to sort the list
newdata = sorted(datatups, key=lambda pair: pair[1], reverse=True)
print("tuples after sorted:", datatups)
print("returned from sorted:", newdata)

shuffled data: [5, 2, 3, 7, 9, 6, 8, 4, 1, 0]
ascending sort: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
descending sort: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
data tuples: [(9, 4), (8, 10), (7, 11), (6, 4), (5, 14), (4, 10), (3, 6), (2, 11), (1, 9), (0, 6)]
sorted data tuples: [(0, 6), (1, 9), (2, 11), (3, 6), (4, 10), (5, 14), (6, 4), (7, 11), (8, 10), (9, 4)]
sorted by second item: [(6, 4), (9, 4), (0, 6), (3, 6), (1, 9), (4, 10), (8, 10), (2, 11), (7, 11), (5, 14)]
sorted by product: [(8, 10), (7, 11), (5, 14), (4, 10), (9, 4), (6, 4), (2, 11), (3, 6), (1, 9), (0, 6)]
shuffled tuples: [(2, 11), (3, 6), (7, 11), (5, 14), (6, 4), (1, 9), (9, 4), (0, 6), (4, 10), (8, 10)]
tuples after sorted: [(2, 11), (3, 6), (7, 11), (5, 14), (6, 4), (1, 9), (9, 4), (0, 6), (4, 10), (8, 10)]
returned from sorted: [(5, 14), (2, 11), (7, 11), (4, 10), (8, 10), (1, 9), (3, 6), (0, 6), (6, 4), (9, 4)]

# Program Tips

In [ ]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 0
"""


# Initialize emperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
mercury = 440
venus = 737
mars = 210

# Compute temperature in Farenheit
mercury_result = (mercury - 275.15) * 9 / 5 + 32
venus_result = (venus - 275.15) * 9 / 5 + 32
mars_result = (mars - 275.15) * 9 / 5 + 32

# Print
print("The daily average temperature on Mercury is", mercury_result, "Farenheit")
print("The daily average temperature on Venus is", venus_result, "Farenheit")
print("The daily average temperature on Mars is", mars_result, "Farenheit")

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

In [4]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 1
"""


# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
mercury = 440
venus = 737
mars = 210

# Compute temperature in Farenheit
def compute_temp(temp):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    return (temp - 275.15) * 9 / 5 + 32

mercury_result = compute_temp(mercury)
venus_result = compute_temp(venus)
mars_result = compute_temp(mars)

# Print out results
print("The daily average temperature on Mercury is", mercury_result, "Farenheit")
print("The daily average temperature on Venus is", venus_result, "Farenheit")
print("The daily average temperature on Mars is", mars_result, "Farenheit")

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.73 Farenheit
The daily average temperature on Venus is 863.3300000000002 Farenheit
The daily average temperature on Mars is -85.26999999999995 Farenheit

In [5]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 2
"""


# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
mercury = 440
venus = 737
mars = 210

# Compute temperature in Farenheit
def compute_temp(temp):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    return (temp - 275.15) * 9 / 5 + 32

mercury_result = compute_temp(mercury)
venus_result = compute_temp(venus)
mars_result = compute_temp(mars)

# Print out results
def print_temp(planet, temp):
    """
    Print out the average daily temps
    """
    print("The daily average temperature on", planet, "is", temp, "Farenheit")
    
print_temp("Mercury", mercury_result)
print_temp("Venus", venus_result)
print_temp("Mars", mars_result)

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.73 Farenheit
The daily average temperature on Venus is 863.3300000000002 Farenheit
The daily average temperature on Mars is -85.26999999999995 Farenheit

In [6]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 3
"""


# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
mercury = 440
venus = 737
mars = 210

# Compute temperature in Farenheit
def compute_celsius(temp):
    """
    Given a floaring point temperature temp in Kelvin,
    return the corresponding temperature in Celsius
    """
    return temp - 275.15

def compute_farenheit(temp):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    temp_celsius = compute_celsius(temp)
    return temp_celsius * 9 / 5 + 32

mercury_result = compute_farenheit(mercury)
venus_result = compute_farenheit(venus)
mars_result = compute_farenheit(mars)

# Print out results
def print_temp(planet, temp):
    """
    Print out the average daily temps
    """
    print("The daily average temperature on", planet, "is", temp, "Farenheit")
    
print_temp("Mercury", mercury_result)
print_temp("Venus", venus_result)
print_temp("Mars", mars_result)

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.73 Farenheit
The daily average temperature on Venus is 863.3300000000002 Farenheit
The daily average temperature on Mars is -85.26999999999995 Farenheit

In [7]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 4
"""


# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
MERCURY_KELVIN = 440
VENUS_KELVIN = 737
MARS_KELVIN = 210

# Compute temperature in Farenheit
def kelvin_to_celsius(temp_kelvin):
    """
    Given a floaring point temperature temp in Kelvin,
    return the corresponding temperature in Celsius
    """
    return temp_kelvin - 275.15

def kelvin_to_farenheit(temp_kelvin):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    temp_celsius = kelvin_to_celsius(temp_kelvin)
    return temp_celsius * 9 / 5 + 32

mercury_farenheit = kelvin_to_farenheit(MERCURY_KELVIN)
venus_farenheit = kelvin_to_farenheit(VENUS_KELVIN)
mars_farenheit = kelvin_to_farenheit(MARS_KELVIN)

# Print out results
def print_temp_farenheit(planet, temp_farenheit):
    """
    Print out the average daily temps in Farenheit
    """
    print("The daily average temperature on", planet, "is", temp_farenheit, "Farenheit")
    
print_temp_farenheit("Mercury", mercury_farenheit)
print_temp_farenheit("Venus", venus_farenheit)
print_temp_farenheit("Mars", mars_farenheit)

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.73 Farenheit
The daily average temperature on Venus is 863.3300000000002 Farenheit
The daily average temperature on Mars is -85.26999999999995 Farenheit

In [8]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 5
"""

# Important constants
ZERO_KELVIN_IN_CELSIUS = -275.15
ZERO_CELSIUS_IN_FARENHEIT = 32
CELSIUS_TO_FARENHEIT_SCALING = 9 / 5

# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
MERCURY_KELVIN = 440
VENUS_KELVIN = 737
MARS_KELVIN = 210

# Compute temperature in Farenheit
def kelvin_to_celsius(temp_kelvin):
    """
    Given a floaring point temperature temp in Kelvin,
    return the corresponding temperature in Celsius
    """
    return temp_kelvin + ZERO_KELVIN_IN_CELSIUS

def kelvin_to_farenheit(temp_kelvin):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    temp_celsius = kelvin_to_celsius(temp_kelvin)
    return temp_celsius * CELSIUS_TO_FARENHEIT_SCALING + ZERO_CELSIUS_IN_FARENHEIT

mercury_farenheit = kelvin_to_farenheit(MERCURY_KELVIN)
venus_farenheit = kelvin_to_farenheit(VENUS_KELVIN)
mars_farenheit = kelvin_to_farenheit(MARS_KELVIN)

# Print out results
def print_temp_farenheit(planet, temp_farenheit):
    """
    Print out the average daily temps in Farenheit
    """
    print("The daily average temperature on", planet, "is", temp_farenheit, "Farenheit")
    
print_temp_farenheit("Mercury", mercury_farenheit)
print_temp_farenheit("Venus", venus_farenheit)
print_temp_farenheit("Mars", mars_farenheit)

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.7300000000001 Farenheit
The daily average temperature on Venus is 863.33 Farenheit
The daily average temperature on Mars is -85.26999999999997 Farenheit

In [9]:
"""
Converting the average daily temperatures for several planets 
from Kelvin to Farenheit --- Version 6
"""

# Important constants
ZERO_KELVIN_IN_CELSIUS = -275.15
ZERO_CELSIUS_IN_FARENHEIT = 32
CELSIUS_TO_FARENHEIT_SCALING = 9 / 5

# Initialize temperatures for various planets
# http://www.smartconversion.com/otherInfo/Temperature_of_planets_and_the_Sun.aspx
MERCURY_KELVIN = 440
VENUS_KELVIN = 737
MARS_KELVIN = 210

# Compute temperature in Farenheit
def kelvin_to_celsius(temp_kelvin):
    """
    Given a floaring point temperature temp in Kelvin,
    return the corresponding temperature in Celsius
    """
    return temp_kelvin + ZERO_KELVIN_IN_CELSIUS

def kelvin_to_farenheit(temp_kelvin):
    """
    Given a floating point temperature temp in Kelvin,
    return the corresponding temperature in Farenheit
    """
    temp_celsius = kelvin_to_celsius(temp_kelvin)
    return temp_celsius * CELSIUS_TO_FARENHEIT_SCALING + ZERO_CELSIUS_IN_FARENHEIT


# Print out results
def print_temp_farenheit(planet, temp_farenheit):
    """
    Print out the average daily temps in Farenheit
    """
    print("The daily average temperature on", planet, "is", temp_farenheit, "Farenheit")

    
# Compute and print results
def compute_and_print_temperatures():
    """
    Compute the temeperatues for three planets in Farenheit
    """
    mercury_farenheit = kelvin_to_farenheit(MERCURY_KELVIN)
    venus_farenheit = kelvin_to_farenheit(VENUS_KELVIN)
    mars_farenheit = kelvin_to_farenheit(MARS_KELVIN)

    print_temp_farenheit("Mercury", mercury_farenheit)
    print_temp_farenheit("Venus", venus_farenheit)
    print_temp_farenheit("Mars", mars_farenheit)

compute_and_print_temperatures()

# Output
##The daily average temperature on Mercury is 328.73 Farenheit
##The daily average temperature on Venus is 863.33 Farenheit
##The daily average temperature on Mars is -85.27 Farenheit

The daily average temperature on Mercury is 328.7300000000001 Farenheit
The daily average temperature on Venus is 863.33 Farenheit
The daily average temperature on Mars is -85.26999999999997 Farenheit